### ISSUE TITLE
C code, Error in bvec

### ISSUE THREAD

**Issue by giadasp** [jwindle/BayesLogit#6]
I was looking at the C code:

```
void PolyaGamma::set_trunc(int trunc)
{
  
  if (trunc < 1) {
  #ifndef NTHROW
    throw std::invalid_argument("PolyaGamma(int trunc): trunc < 1.");
  #else
    #ifndef USE_R
    fprintf(stderr, "Invalid parameter: PolyaGamma(int trunc): trunc < 1.  Setting trunc=1.\n");
    #else
    Rprintf("Invalid parameter: PolyaGamma(int trunc): trunc < 1.  Setting trunc=1.\n");
    #endif
    trunc = 1;
  #endif
  }
  
  T = trunc;
  bvec.resize(T);

  for(int k=0; k < T; ++k){
    // + since we start indexing at 0.
    double d = ((double) k + 0.5);
    bvec[k] = FOURPISQ * d * d;
  }
} // set_trunc
```

and I noticed that `d = ((double) k + 0.5);` should be equal to `d = ((double) k - 0.5);` as in the R code.
I hope this can be helpful.

**Comment by coatless** [comment]
@giadasp I think you are correct here. It should indeed be `+` instead of `-`.

The R version has `(1:trunc-1/2)^2` :
https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/R/PolyaGamma.R#L261-L271

while the C++ version has `(1:trunc+1/2)^2`:

https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/src/PolyaGamma.cpp#L54-L61

@jwindle thoughts on patching this difference?

**Comment by coatless** [comment]
@giadasp I don't think that is an issue because

The R version has `(1:trunc-1/2)^2` :
https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/R/PolyaGamma.R#L261-L271

while the C++ version has `(0:(trunc-1) - 1/2 + 1)^2` where the `+ 1` covers the index shift and results in `+ 1/2` instead of `-1/2`. That's why I think Jesse left the `// + since we start indexing at 0.` comment:

https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/src/PolyaGamma.cpp#L54-L61

**Comment by giadasp** [comment]
Oh, I understand. Thank you for the clarification.
